version: "3.9"

# GPU Worker Services - Runs on workstation with RTX 4070 Ti
# Provides LLM inference for Birtha server orchestrator

services:
  # vLLM LLM Runner - High-performance LLM inference
  llm-runner:
    image: vllm/vllm-openai:latest
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - HF_TOKEN=${HF_TOKEN:-}
      - CUDA_VISIBLE_DEVICES=0
      - LLM_BACKEND=vllm
      - ENABLE_GPU=true
    command:
      [
        "--model", "${VLLM_MODEL:-mistralai/Mistral-7B-Instruct-v0.3}",
        "--dtype", "float16",
        "--max-model-len", "${VLLM_MAX_MODEL_LEN:-8192}",
        "--gpu-memory-utilization", "${VLLM_GPU_MEMORY_UTILIZATION:-0.92}",
        "--enable-prefix-caching",
        "--host", "0.0.0.0",
        "--port", "8000"
      ]
    ports:
      - "${WORKER_VLLM_PORT:-8000}:8000"
    runtime: nvidia
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Ollama LLM Runner (alternative to vLLM for development)
  ollama-runner:
    image: ollama/ollama:latest
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3:8b-instruct-q4_K_M}
      - OLLAMA_ORIGINS=*
      - OLLAMA_KEEP_ALIVE=24h
      - LLM_BACKEND=ollama
      - ENABLE_GPU=true
    ports:
      - "${WORKER_OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama_data:/root/.ollama
    runtime: nvidia
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    profiles:
      - ollama  # Use --profile ollama to enable

  caddy:
    image: caddy:2-alpine
    ports:
      - "${WORKER_PROXY_PORT:-8443}:8443"
    volumes:
      - ./infra/reverse-proxy/Caddyfile.worker:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - llm-runner
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  ollama_data:
