name: "✨ Feature request"
description: Propose a new feature
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What’s the user problem?
    validations: { required: true }
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Describe your solution and alternatives considered
    validations: { required: true }
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet list of testable outcomes
