# MCP Servers Configuration
# Global MCP servers for Birtha + WrkHrs AI stack
# Environment variables are substituted using ${VAR_NAME} syntax

servers:
  # GitHub MCP Server - Project management and repository operations
  - name: mcp-github
    type: tool
    description: GitHub project management and repository operations
    version: 1.0.0
    url: http://mcp-github:7000
    health_url: http://mcp-github:7000/health
    tools:
      - name: create_issue
        description: Create a new GitHub issue
        schema:
          type: object
          properties:
            title:
              type: string
            body:
              type: string
            labels:
              type: array
              items:
                type: string
      - name: create_pull_request
        description: Create a new pull request
        schema:
          type: object
          properties:
            title:
              type: string
            body:
              type: string
            head:
              type: string
            base:
              type: string
      - name: search_repositories
        description: Search GitHub repositories
        schema:
          type: object
          properties:
            query:
              type: string
            sort:
              type: string
              enum: [stars, forks, updated]
    resources: []
    metadata:
      env:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        GITHUB_ORG: ${GITHUB_ORG}
        GITHUB_REPO: ${GITHUB_REPO}
        DEFAULT_PROJECT_NUMBER: ${GITHUB_PROJECT_NUMBER}

  # Filesystem MCP Server - File and directory operations
  - name: mcp-filesystem
    type: tool
    description: Filesystem operations and code analysis
    version: 1.0.0
    url: http://mcp-filesystem:7001
    health_url: http://mcp-filesystem:7001/health
    tools:
      - name: read_file
        description: Read contents of a file
        schema:
          type: object
          properties:
            path:
              type: string
      - name: write_file
        description: Write contents to a file
        schema:
          type: object
          properties:
            path:
              type: string
            content:
              type: string
      - name: list_directory
        description: List directory contents
        schema:
          type: object
          properties:
            path:
              type: string
            recursive:
              type: boolean
      - name: code_analysis
        description: Analyze code structure and dependencies
        schema:
          type: object
          properties:
            path:
              type: string
            language:
              type: string
    resources:
      - name: workspace_files
        description: Access to workspace files
        mime_type: text/plain
    metadata:
      env:
        WORKSPACE_PATH: ${WORKSPACE_PATH:-/workspace}

  # Secrets MCP Server - Secure credential management
  - name: mcp-secrets
    type: resource
    description: Secure credential and secret management
    version: 1.0.0
    url: http://mcp-secrets:7002
    health_url: http://mcp-secrets:7002/health
    tools:
      - name: get_secret
        description: Retrieve a secret value
        schema:
          type: object
          properties:
            key:
              type: string
      - name: set_secret
        description: Store a secret value
        schema:
          type: object
          properties:
            key:
              type: string
            value:
              type: string
    resources:
      - name: secrets
        description: Encrypted secrets storage
        mime_type: application/json
    metadata:
      env:
        SECRETS_BACKEND: ${SECRETS_BACKEND:-file}
        SECRETS_PATH: ${SECRETS_PATH:-/secrets}

  # Vector Database MCP Server - Embedding search and storage
  - name: mcp-vector-db
    type: tool
    description: Vector database operations for semantic search
    version: 1.0.0
    url: http://mcp-vector-db:7003
    health_url: http://mcp-vector-db:7003/health
    tools:
      - name: embedding_search
        description: Search for similar embeddings
        schema:
          type: object
          properties:
            text:
              type: string
            top_k:
              type: integer
              default: 5
            threshold:
              type: number
              default: 0.7
      - name: store_embedding
        description: Store text with embeddings
        schema:
          type: object
          properties:
            text:
              type: string
            metadata:
              type: object
      - name: delete_embedding
        description: Delete embeddings by ID
        schema:
          type: object
          properties:
            id:
              type: string
    resources:
      - name: embeddings
        description: Vector embeddings storage
        mime_type: application/json
    metadata:
      env:
        VECTOR_DB_URL: ${VECTOR_DB_URL:-http://qdrant:6333}
        EMBEDDING_MODEL: ${EMBEDDING_MODEL:-sentence-transformers/all-MiniLM-L6-v2}

  # Code Resources MCP Server - Code analysis and documentation
  - name: mcp-code-resources
    type: tool
    description: Code analysis, documentation generation, and repository insights
    version: 1.0.0
    url: http://mcp-code-resources:7004
    health_url: http://mcp-code-resources:7004/health
    tools:
      - name: analyze_code
        description: Analyze code structure and complexity
        schema:
          type: object
          properties:
            path:
              type: string
            language:
              type: string
      - name: generate_docs
        description: Generate documentation for code
        schema:
          type: object
          properties:
            path:
              type: string
            format:
              type: string
              enum: [markdown, rst, html]
      - name: find_dependencies
        description: Find code dependencies and imports
        schema:
          type: object
          properties:
            path:
              type: string
    resources:
      - name: code_analysis
        description: Code analysis results
        mime_type: application/json
    metadata:
      env:
        WORKSPACE_PATH: ${WORKSPACE_PATH:-/workspace}

  # Document Resources MCP Server - Document processing and analysis
  - name: mcp-doc-resources
    type: tool
    description: Document processing, analysis, and content extraction
    version: 1.0.0
    url: http://mcp-doc-resources:7005
    health_url: http://mcp-doc-resources:7005/health
    tools:
      - name: extract_text
        description: Extract text from documents
        schema:
          type: object
          properties:
            path:
              type: string
            format:
              type: string
              enum: [pdf, docx, txt, md]
      - name: summarize_document
        description: Generate document summary
        schema:
          type: object
          properties:
            path:
              type: string
            max_length:
              type: integer
              default: 200
      - name: extract_metadata
        description: Extract document metadata
        schema:
          type: object
          properties:
            path:
              type: string
    resources:
      - name: documents
        description: Processed document content
        mime_type: text/plain
    metadata:
      env:
        DOCS_PATH: ${DOCS_PATH:-/docs}
