# MCP Servers Configuration
# This file defines the global MCP servers available to the router

servers:
  - name: github-mcp
    type: http
    url: http://mcp-github:7000
    description: "GitHub integration for repository operations"
    capabilities:
      - repository_management
      - issue_tracking
      - pull_request_operations
      - code_search

  - name: filesystem-mcp
    type: http
    url: http://mcp-filesystem:7001
    description: "File system operations and code analysis"
    capabilities:
      - file_read_write
      - directory_traversal
      - code_analysis
      - dependency_analysis
    config:
      # Optional context paths for documents (marker)
      marker_docs_dir: /mnt/appdata/addons/documents
      marker_processed_dir: /mnt/appdata/addons/documents_processed

  - name: secrets-mcp
    type: http
    url: http://mcp-secrets:7002
    description: "Secure secrets management and retrieval"
    capabilities:
      - secret_retrieval
      - credential_management
      - environment_variables
      - vault_integration

  - name: vector-db-mcp
    type: http
    url: http://mcp-vector-db:7003
    description: "Vector database operations for embeddings and search"
    capabilities:
      - embedding_search
      - vector_storage
      - similarity_search
      - knowledge_retrieval

# Global server settings
global_settings:
  timeout: 30
  retry_attempts: 3
  health_check_interval: 60
  max_concurrent_requests: 10
